# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 22:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overseer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dummy', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dummy', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='ci',
            field=models.CharField(default=123456789, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='direction',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 1), (1, 2)], default=1),
            preserve_default=False,
        ),
    ]
