# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180202_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 1), (1, 2)], default=1),
        ),
    ]
