# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180205_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 1), (1, 2)], default=None, null=True),
        ),
    ]
