# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-31 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180205_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='direction',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Worker'), (2, 'Overseer')], default=None, null=True),
        ),
    ]
