# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-26 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180926_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overseer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.DeleteModel(
            name='Overseer',
        ),
    ]
