# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='tasks',
            field=models.ManyToManyField(related_name='enabled_tasks', to='tracker.Task'),
        ),
        migrations.AddField(
            model_name='loghour',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracker.Task'),
            preserve_default=False,
        ),
    ]
