# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20180205_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='logs',
            field=models.ManyToManyField(to='tracker.LogHour'),
        ),
    ]
