# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20180222_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='building',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracker.Building'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workday',
            name='logs',
            field=models.ManyToManyField(to='tracker.LogHour'),
        ),
    ]
