# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20180222_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='assigned',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workday',
            name='logs',
            field=models.ManyToManyField(to='tracker.LogHour'),
        ),
    ]
