# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-31 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20180223_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='logs',
            field=models.ManyToManyField(blank=True, to='tracker.LogHour'),
        ),
    ]
