# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-31 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20180831_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='direction',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='workday',
            name='logs',
            field=models.ManyToManyField(blank=True, to='tracker.LogHour'),
        ),
    ]
