# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-07 14:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_auto_20180831_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='tasks',
            field=models.ManyToManyField(related_name='buildings', to='tracker.Task'),
        ),
        migrations.AlterField(
            model_name='building',
            name='workers',
            field=models.ManyToManyField(related_name='buildings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workday',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='workday',
            name='logs',
            field=models.ManyToManyField(blank=True, related_name='workday', to='tracker.LogHour'),
        ),
    ]
