# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-07 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_auto_20180907_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='logs',
        ),
        migrations.AddField(
            model_name='loghour',
            name='workday',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tracker.Workday'),
            preserve_default=False,
        ),
    ]
