# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-26 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_auto_20180926_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerCategory',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'worker categories',
            },
        ),
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'verbose_name_plural': 'task categories'},
        ),
        migrations.AddField(
            model_name='worker',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.WorkerCategory'),
        ),
    ]
