# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-26 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_auto_20180926_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loghour',
            name='user',
        ),
        migrations.AddField(
            model_name='loghour',
            name='worker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracker.Worker'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='workers',
            field=models.ManyToManyField(related_name='buildings', to='tracker.Worker'),
        ),
    ]
