# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-28 13:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_auto_20180926_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loghour',
            name='amount',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(1)]),
        ),
    ]
