# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-01 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_workday_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workday',
            old_name='name',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='workday',
            name='force_finished',
            field=models.BooleanField(default=False),
        ),
    ]
