# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-02 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0027_auto_20181001_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='holiday',
            field=models.BooleanField(default=False),
        ),
    ]
