# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-03 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0030_task_is_boolean'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='whole_day',
            field=models.BooleanField(default=False),
        ),
    ]
