# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-17 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0031_task_whole_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='in_monthly_report',
            field=models.BooleanField(default=True),
        ),
    ]
