# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-11 19:43
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0033_auto_20181111_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'building', 'verbose_name_plural': 'buildings'},
        ),
        migrations.AlterModelOptions(
            name='loghour',
            options={'verbose_name': 'log hour', 'verbose_name_plural': 'log hours'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'verbose_name': 'task category', 'verbose_name_plural': 'task categories'},
        ),
        migrations.AlterModelOptions(
            name='workday',
            options={'verbose_name': 'workday', 'verbose_name_plural': 'workdays'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'worker', 'verbose_name_plural': 'workers'},
        ),
        migrations.AlterModelOptions(
            name='workercategory',
            options={'verbose_name': 'worker category', 'verbose_name_plural': 'worker categories'},
        ),
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='building',
            name='code',
            field=models.PositiveIntegerField(verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='building',
            name='overseer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Capataz'),
        ),
        migrations.AlterField(
            model_name='building',
            name='tasks',
            field=models.ManyToManyField(related_name='buildings', to='tracker.Task', verbose_name='Tasks'),
        ),
        migrations.AlterField(
            model_name='building',
            name='workers',
            field=models.ManyToManyField(related_name='buildings', to='tracker.Worker', verbose_name='Workers'),
        ),
        migrations.AlterField(
            model_name='loghour',
            name='amount',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(1)], verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='loghour',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='loghour',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Task', verbose_name='task'),
        ),
        migrations.AlterField(
            model_name='loghour',
            name='workday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tracker.Workday', verbose_name='workday'),
        ),
        migrations.AlterField(
            model_name='loghour',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Worker', verbose_name='worker'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.TaskCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='in_monthly_report',
            field=models.BooleanField(default=True, verbose_name='in monthly report'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_boolean',
            field=models.BooleanField(default=False, verbose_name='is boolean'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='requires_comment',
            field=models.BooleanField(default=False, verbose_name='requires comment'),
        ),
        migrations.AlterField(
            model_name='task',
            name='whole_day',
            field=models.BooleanField(default=False, verbose_name='whole day'),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='name',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Building', verbose_name='Building'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=400, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='finished'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='force_finished',
            field=models.BooleanField(default=False, verbose_name='force finished'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='holiday',
            field=models.BooleanField(default=False, verbose_name='holiday'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.WorkerCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='workercategory',
            name='name',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='name'),
        ),
    ]
