# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-22 14:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0034_auto_20181111_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='overseer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Overseer'),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='name',
            field=models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='name'),
        ),
    ]
