# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-22 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0035_auto_20181122_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.CharField(max_length=60, unique=True, verbose_name='code'),
        ),
    ]
