# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-22 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0037_auto_20181218_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='workercategory',
            name='code',
            field=models.CharField(default='def', max_length=10, verbose_name='code'),
            preserve_default=False,
        ),
    ]
