# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-22 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0038_workercategory_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workercategory',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='code'),
        ),
    ]
